# Generated by Django 3.2.2 on 2021-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
