# Generated by Django 3.2.3 on 2021-05-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_city'),
        ('cities', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
