# Generated by Django 3.2.2 on 2021-05-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('taken_seats', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.city')),
            ],
        ),
    ]
